### ISSUE TITLE
Request to port to API 7, please.

### ISSUE THREAD

**Issue by Wissi** [Proxying/TabManager#12]
Love your plugin, we have it on our servers. 
We're moving over to 1.12 and would love to keep using your plugin, Would you consider updating/porting it over to API 7, please?

**Comment by aWitch-Doctor** [comment]
I am using this on the latest build of sponge vanilla api 7 and it seems to work just fine for me. Are you getting errors?

**Comment by aWitch-Doctor** [comment]
Update, I loaded placeholderapi 4.2 and nucleus gluon 1.0.3 on the server and one of the 2 caused tab manager to break. I removed them and tab manager worked fine again. Not sure whats happening and since i don't actually need either of those, I'll just leave them off so I can keep tab manager.

**Comment by randombyte-developer** [comment]
@Wissi So everything works?

**Comment by Wissi** [comment]
Yes, thank you so much for your quick response. It seems to be working fine for the simple, yet important  use we give it.

We love your work. thank you.

**Comment by randombyte-developer** [comment]
Lol, I'm not even the owner of the plugin and my response was everything but quick.
