### ISSUE TITLE
Multiline tabs

### ISSUE THREAD

**Issue by xion87** [Proxying/TabManager#15]
Is possible to create multiline title/footer with TabManager? Like titlemanager does

Thank you!

**Comment by Proxying** [comment]
It's possible already by using JSON format. If you google JSON newline format you should find the character and be able to copy/paste it into the config to generate a new line.

**Comment by Proxying** [comment]
Yeah like that, you'd have to copy the character codes exactly from the json website and you should be good.

**Comment by xion87** [comment]
yep is \n :³ ty
