### ISSUE TITLE
 Top group is down, And default group is up

### ISSUE THREAD

**Issue by ClarkHalf** [Proxying/TabManager#18]

**Comment by Proxying** [comment]
?

**Comment by ClarkHalf** [comment]
Sorry, is that the top group is below the default group and the other group, the tab is all decolumnated. I would like to put the owner first and default the last one how do I do it?

**Comment by ClarkHalf** [comment]
@Proxying

**Comment by Proxying** [comment]
To “group” players in the Tab List by their permission group (via Luckperms, ZPermissions, whatever), enable “Add Players to Teams” in your main tabmanager.conf file. This will automagically enable grouping with other players of the same group.

**Comment by ClarkHalf** [comment]
# This will add players on the server to Teams within the scoreboard, this will override custom tab menus such as the Pixelmon GUI. Allowing for custom prefix/suffix within that. HOWEVER, this will also give the player a prefix and/or suffix while chatting in-game, so a plugin like Nucleus will have to also be used to handle chat if you want it to look different from your options here.
    "Add Players to Teams"=true



I already added and the guide is still messy

**Comment by Proxying** [comment]
The tabs are sorted from 0-9, A-Z by MC. So you'll have to mess around with group names in the config file if you want them in a certain order.

**Comment by ClarkHalf** [comment]
So I need to put for example a-founder and bdefault

**Comment by Proxying** [comment]
Yes, or 0founder, 1default

**Comment by ClarkHalf** [comment]
![image](https://user-images.githubusercontent.com/47356413/56319146-40d04f80-6137-11e9-8965-be90513623be.png)

![image](https://user-images.githubusercontent.com/47356413/56319159-49c12100-6137-11e9-991d-5806db20a0fe.png)


What's wrong?

**Comment by ClarkHalf** [comment]
AVIP is to be down, but it does not stay down.

**Comment by Proxying** [comment]
Put the 0-9 or a-z before the group name.

**Comment by ClarkHalf** [comment]
But as you can see, there is a a and b before VIPs. And yet the A is below B

**Comment by ClarkHalf** [comment]
![image](https://user-images.githubusercontent.com/47356413/56319367-df5cb080-6137-11e9-8d86-85e23ec88398.png)



Now I've changed the players of the groups, and it seems that the nick Couriedoll always comes before the Poox, and so does not change their position on the tab
