### ISSUE TITLE
/vanish with tab menu.

### ISSUE THREAD

**Issue by aWitch-Doctor** [Proxying/TabManager#2]
Can you make it so if a player is vanished with nucleus or any other plugins vanish command their name is removed from the tab menu? Possibly a permission for this?

Also add a config setting to show multiple tags in a set order only if the tag is present. So the server has 5 different possible tag groups but depending on the player and what they do/are they will only have some of the tag groups. So a we have a players [rank] [division] [donator] and [specialty]. [rank] has 6 different possible tags, [division] has 6 possible tags, [donator] has 1, and [specialty] has 5. I would like to be able to show only one tag from each group the player is part of. In lucky perms I was able to add each group to it's own track to accomplish this. Can you add something like that?

And last request, add a config setting on whether or not the tab menu should show the players nickname assigned by nucleus or any other plugin.

I know this is a lot and I really appreciate your time and effort on this plugin. Anything you can do is would be amazing.

**Comment by Proxying** [comment]
I'm unsure how Nucleus handles their vanish and nicknames (I think they do most of it internally so to do that Nucleus would have to be a dependency in the plugin, unless they updated their nickname code). As for the multiple tags I can see what I can do in regards to that, some of it may align with the other opened request for ordered tags.

**Comment by aWitch-Doctor** [comment]
I do think they other request will tie into the multiple prefixes but that's only half of it. 

Thank you

**Comment by aWitch-Doctor** [comment]
Mkay, so i took a look around and nucleus saves the nickname in a json file. 

Server directory/nucleus/userdata/(folder starting with the first 2 characters of the players UUID)/(players UUID).json

Then the file has this entry for it.
"nickname": "Blah_Blah",

Any way you can have tab manager check to see if this line exists for a player and if so display that name. If this is possible please set config settings to display nickname or user name and also a setting for what to display in front of a nick name. For instance nucleus lets you choose what characters are in front of the nickname to show that it is a nickname, I think default is "~" So I would be ~Witch

I have no clue how much work this would be or if it is even possible, just wanted to try to make it a little easier. Thank you again for all your hard work on making these plugins.

**Comment by aWitch-Doctor** [comment]
It seems like vanish is already working somewhat. Nucleus must stop the server from sending the vanish name all together so you shouldn't really need to add this feature, just make it so tab manager updates the player list once the vanish command is ran. This is a guess, I'm still trying to figure it out.

**Comment by Proxying** [comment]
Vanish will hook into another request then, of automatic refreshes/updates on a configurable timer. As for nickname, I'll try and do it via the player object first, if it's not possible with the way nucleus handles it, I'll use their save file.

Thanks for taking the time to look into it.

**Comment by aWitch-Doctor** [comment]
No problem, anything I can do to help. 

I'm asking nucleus to allow players with a specific permission to still see vanished players in tab but I dont know how this will happen or how it will affect your plugin. I'm guessing don't worry about that until nucleus updates.

Again, thank you for all your hard work on this plugin.

**Comment by Proxying** [comment]
Nickname section now filled with https://github.com/Proxying/TabManager/releases/tag/2.0.0.

**Comment by Proxying** [comment]
Vanish stuff fixed as of 2.1.3 

https://github.com/Proxying/TabManager/releases/tag/2.1.3
