### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ClarkHalf** [Proxying/TabManager#20]
![image](https://user-images.githubusercontent.com/47356413/56432308-3fbc3100-62a3-11e9-9023-9eeccb49a485.png)

A player who bought vip TRAINER has the nick Slenderpro123, When he logs into the server with this nick he drops all of the server giving a max lenght bug

**Comment by ClarkHalf** [comment]
VIP "TREINADOR"

**Comment by Proxying** [comment]
Shorten the size of the group name. That's a default minecraft limitation of 16 characters.
