### ISSUE TITLE
Console Spam / Header and Footer not working.

### ISSUE THREAD

**Issue by MrBringBacon** [Proxying/TabManager#25]
Just wondering why this issue is happening.
[OneControlCenter] [06:20:43] [Server thread/INFO] [tabmanager]: placeholder service null?

Here's a latest.log - https://pastebin.com/kMbqdLVV
Here's the config - https://pastebin.com/gQBZPsaS
Here's it not working in game - https://imgur.com/a/1xBw6oX

spongeforge-1.12.2-2838-7.1.7-RC3924.jar
TabManager-2.1.3-S7.0-MC1.12.2.jar
PlaceholderAPI-4.5.1.jar
pixelmonplaceholders-2.1.3.jar

**Comment by Proxying** [comment]
PlaceholderAPI failed to start up properly as shown in your latest.log. Check your PlaceholderAPI config files for issues.

**Comment by Proxying** [comment]
https://pastebin.com/psK0yfp9 here is the exact issue for reference.

**Comment by MrBringBacon** [comment]
Alright so first off, thank you for that. I deleted the PlaceholderAPI Config, restarted the server.. everything worked.

The server then does it's automatic restart without me deleting the config, gets back up. It's all broke again.

Do you by chance know why this is happening? 
If I delete the PlaceholderAPI Config it's all normal but if I don't and server restarts.. it's broke.

**Comment by Proxying** [comment]
Sorry, I don't make nor edit PlaceHolderAPI. You'd have to look in your logs and control+f for PlaceHolderAPI, see where its having an issue then make an issue on their github.
