### ISSUE TITLE
Reload Tabs Automatically

### ISSUE THREAD

**Issue by SubtypeZero** [Proxying/TabManager#3]
Could you make it so that the tab list refreshes at a configurable time interval? It could be disabled by default, but I think it would be a nice feature to have. It's definitely something I'd like to have on my servers, since I don't have to have to manually refresh the tab list every time I change something in the config or add a user to a group

**Comment by Proxying** [comment]
Yep I can definitely get that added in the near future.

**Comment by randombyte-developer** [comment]
This can be easily added now since 4e8d60e. The config only needs to be refreshed when the update task  is called.

**Comment by randombyte-developer** [comment]
@Proxying This can be closed
