### ISSUE TITLE
Adding PlaceholderAPI support

### ISSUE THREAD

**Issue by randombyte-developer** [Proxying/TabManager#5]
Hi @Proxying!

Could you add support for [PlaceholderAPI](https://github.com/rojo8399/PlaceholderAPI/wiki/Developers)? If you don't want to do it yourself, please guide me in a direction where I could intercept your code setting the tab's text.

**Comment by Proxying** [comment]
https://github.com/Proxying/TabManager/blob/master/src/main/java/uk/co/proxying/tabmanager/utils/Utilities.java#L70 This is called upon player login and sets the tab text objects for them and the other plkayers on the server. If you'd like I'd be more than happy to merge a PR in that implements placeholder API, just remember to add yourself to the author list if you're submitting something so people know who to thank for helping.

**Comment by randombyte-developer** [comment]
Thanks, I will try.
